### ISSUE TITLE
Investigate external trigger issue

### ISSUE THREAD

**Issue by paul-richardson-clf** [CentralLaserFacility/ADPixci#77]
Identify and fix issue that is preventing the 1k raptor camera from repeatedly capturing on an external trigger.
As demoed the camera triggers once on an external trigger, then stops responding to other triggers. If it was switched to live, then back to external triggers it worked ok.

Also identify and fix the fact on start up the GUI displays the status as external trigger, when it's actually set to live running.

Test on both the 1k and 2k camera versions:
1. The external trigger mode is working correctly & repeatedly, using the setup in R2 lab under Mags supervision.
2. The GUI is showing the correct trigger mode, even on startup and Mags is happy with the information displayed.
```[tasklist]
### Tasks
- [x] Identify how to make 1k camera work consistently with external trigger
- [x] Check visual bugs
- [x] Check trigger bugs
- [x] Investigate pixi source code to find potential culprits for problems
```

**Comment by irierr** [comment]
### Progress update

**Reliable way to make the external trigger work:**
1. Go into trigger tab
2. Select Ext triggered and falling edge, even if they are already selected and are showing in the RBV field
3. Press acquire to enable acquire mode
4. Can now externally trigger camera
5. Press stop to turn off acquire mode

**Bugs:**
- After pressing acquire, the first trigger pulse does not work, whether in live mode or external trigger mode.
- After pressing stop, you can trigger once more in external trigger mode and sometimes twice more in live mode.
- If in external trigger mode and acquiring mode, and stop is pressed, then no trigger pulse is sent before turning acquire mode back on, the first trigger pulse will work and an image will be acquired, but after that no more images will be acquired until acquiring mode is turned off (no extra trigger pulses will go through at this point unlike behaviour from previous points) and turned back on again - then goes back to behaviour specified in points above. 
- Button trigger mode doesn't heed acquire settings sometimes. The behaviour of this mode seems complex and for now I chose not to investigate it further as Mags had mentioned that it is a useless mode anyway - can revisit if necessary.
- On restart of IOC and GUI, the dropdown and RBV field will display the mode that was selected in the last session, however if you press acquire, it acts as if it is in live mode, no matter what mode is shown.
  - PV's reflect GUI when checked from CLI.
  - If trigger mode is selected again then it resolves this issue.
  - Polarity option from external trigger mode saves its state in the RBV field but not in the dropdown - minor issue but potentially worth investigating further.

**Comment by irierr** [comment]
**Investigation into bugs:**
- Development environment on Raptor PC is needed to debug issues.
- CentralLaserFacility/raptorCamera#23 created for this.
- Blocked until this is done.

**Comment by irierr** [comment]
### ADPixci Source Code Investigation
- getTriggerStatus() defined in pixi.h but not implemented anywhere 
  - Should be in pixi.cpp
  - could be why trigger status shows last mode used in IOC on start up but is not actually reflective of the current mode on the device
- addToParamQue() is overloaded with different types for arguments, but the header and cpp file argument signatures do not match up.
  - have fixed but needs looking into more, especially as implementation is same for both
- writeInt32() seems to be where acquire mode is turned on/off
  - if block at 1911 - 1924 of pixi.cpp looks like it could be the reason that different trigger modes have different behaviour in stopping acquiring.
- paramTask() also has some functionality related to setting trigger mode and sending soft triggers
- acquireImage() & acquireStop() could also be culprits
- writeSerial() not implemented
  - not sure if this is needed as writeReadSerial is implemented and writes then reads, which seems more useful.
- acquireTask() section on imageCounter and numImagesCounter could be worth investigating.
